version: "3.8"
#Change later 
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

 
  #USER SERVICE (port 8001)
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
      
    environment:
      - REDIS_HOST = redis
      - REDIS_PORT = 6379
    
    depends_on:
      - redis

    restart: unless_stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


#TASK SERVICES PORT 8002

task-service:
  build: ./task-service

container_name: task-service

ports:
  - 8002:8002

environment:
  - USER_SERVICE_HOST = user_service
  - USER_SERVICE_PORT = 8001

depends_on:
  - user_service

restart: unless_stopped


#SCHEDULING SERVICES (PORT 8003)
scheduler_service:
 build: ./scheduler-service

 container_name: scheduler_service

 ports:
  - 8003:8003

 environment:
  - USER_SERVICE_HOST = user_service
  - USER_SERVICE_PORT = 8001
  - TASK_SERVICE_HOST = task_service
  - TASK_SERVICE_PORT = 8002

 depends_on:
  - user_service
  - task_service

 restart: unless_stopped