

services:
  # USER SERVICE (port 8001)
  user-service:
    build:
      context: ./service1
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # TASK SERVICE (port 8002)
  task-service:
    build:
      context: ./service2
      dockerfile: Dockerfile
    container_name: task-service
    ports:
      - "8002:8002"
    environment:
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=8001
    depends_on:
      - user-service
    restart: always

  # SCHEDULER SERVICE (port 8003)
  scheduler-service:
    build:
      context: ./service3
      dockerfile: Dockerfile
    container_name: scheduler-service
    ports:
      - "8003:8003"
    environment:
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=8001
      - TASK_SERVICE_HOST=task-service
      - TASK_SERVICE_PORT=8002
    depends_on:
      - user-service
      - task-service
      - redis
    restart: always

  # REDIS SERVICE
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
